name: Delete Old Folders from github pages

on:
  workflow_dispatch:
    inputs:
        n_days:
            description: 'Number of days to determine which folders to delete. Example: 10 will delete all folders older than 10 days'
            required: true
            default: 10
        folder_name:
            description: 'Name of the folder where you store the reports'
            required: true
            default: 'reports'

jobs:
  delete_old_folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
            ref: gh_pages 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # - name: Download the script
      #   run: |
      #     curl -LJO https://raw.githubusercontent.com/adrianmaciuc/rm_old_folders/main/rm_old_folders.py

      - name: Pray then Run the script
        run: python rm_old_folders.py --n-days ${{ github.event.inputs.n_days }} --folder-name ${{ github.event.inputs.folder_name }}