name: Playwright-Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  playwright-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1/2, 2/2]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test --shard ${{ matrix.shard }}

    - name: Upload blob report to GitHub Actions Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: merged-reports-as-blob-$(date '+%F-%H-%M-%S')
        path: blob-report
        retention-days: 90

  merge-reports-and-publish:
  # Merge reports after playwright-tests, even if some shards have failed
     
    if: always()
    needs: [playwright-tests]
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci

    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v3
      with:
        name: merged-reports-as-blob
        path: merged-reports-as-blob

    - name: Merge into HTML Report
      run: npx playwright merge-reports --reporter html ./merged-reports-as-blob

    - name: Upload HTML Report from folder generated by playwright merge-reports method
      uses: actions/upload-pages-artifact@v2
      with:
        path: './playwright-report'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

    - name: Access the report at this URL
      run: echo "${{ steps.deployment.outputs.page_url }}"





        